import React from "react";
import "./RoutineListComponent.scss";
import { ExerciseRoutine } from "../../types/ExerciseRoutine";

interface RoutineListProps {
  //allowing undefined because routine isn't generated by default, could add default empty initialized routine to rid of this
  exerciseRoutine?: ExerciseRoutine;
}

const RoutineListComponent: React.FC<RoutineListProps> = ({
  exerciseRoutine,
}: RoutineListProps) => {
  return (
    <>
      <h1>Routine</h1>
      <div className="display-list">
        {/* {exerciseRoutine.map((item, index) => (
          <div key={index}>{item}</div>
        ))} */}
        {exerciseRoutine?.chestExercises.map((item, index) => (
          <div key={index}>{item.name}</div>
        ))}
      </div>
    </>
  );
};

export default RoutineListComponent;
